

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;


@WebServlet("/index")
public class indexPage extends HttpServlet {
	private static final long serialVersionUID = 1L;

	
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		Cookie c[]=request.getCookies();
		String user="";
		for(Cookie co:c) {
			if(co.getName().equals("name")) {
				user=co.getValue();
			}
		}
		response.setContentType("text/html");
		PrintWriter out=response.getWriter();
		out.println("<!DOCTYPE html>\n"
				+ "<html lang=\"en\">\n"
				+ "<head>\n"
				+ "    <meta charset=\"UTF-8\">\n"
				+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
				+ "    <title>Bookly</title>\n"
				+ "\n"
				+ "    <link rel=\"stylesheet\" href=\"https://unpkg.com/swiper@7/swiper-bundle.min.css\" />\n"
				+ "\n"
				+ "    <!-- font awesome cdn link  -->\n"
				+ "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\">\n"
				+ "\n"
				+ "    <!-- custom css file link  -->\n"
				+ "    <link rel=\"stylesheet\" href=\"style.css\">\n"
				+ "\n"
				+ "\n"
				+ "    <style>\n"
				+ "        .dropbtn {\n"
				+ "          background-color: #4CAF50;\n"
				+ "          color: white;\n"
				+ "          padding: 16px;\n"
				+ "          font-size: 16px;\n"
				+ "          border: none;\n"
				+ "          cursor: pointer;\n"
				+ "        }\n"
				+ "        \n"
				+ "        .dropdown {\n"
				+ "          position: relative;\n"
				+ "          display: inline-block;\n"
				+ "        }\n"
				+ "        \n"
				+ "        .dropdown-content {\n"
				+ "          display: none;\n"
				+ "          position: absolute;\n"
				+ "          background-color: #f9f9f9;\n"
				+ "          min-width: 160px;\n"
				+ "          box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\n"
				+ "          z-index: 1;\n"
				+ "        }\n"
				+ "        \n"
				+ "        .dropdown-content a {\n"
				+ "          color: black;\n"
				+ "          padding: 10px 13px;\n"
				+ "          text-decoration: none;\n"
				+ "          display: block;\n"
				+ "        }\n"
				+ "        \n"
				+ "        .dropdown-content a:hover {background-color: #f1f1f1}\n"
				+ "        \n"
				+ "        .dropdown:hover .dropdown-content {\n"
				+ "          display: block;\n"
				+ "        }\n"
				+ "        \n"
				+ "        /* .dropdown:hover .dropbtn {\n"
				+ "          background-color: #3e8e41;\n"
				+ "        } */\n"
				+ "        </style>\n"
				+ "</head>\n"
				+ "<body>\n"
				+ "\n"
				+ "<!-- header section starts  -->\n"
				+ "\n"
				+ "<header class=\"header\">\n"
				+ "\n"
				+ "    <div class=\"header-1\">\n"
				+ "\n"
				+ "        <a href=\"#\" class=\"logo\"> <i class=\"fas fa-book\"></i> bookly </a>\n"
				+ "\n"
				+ "        <form action=\"\" class=\"search-form\">\n"
				+ "            <input type=\"search\" name=\"\" placeholder=\"search here...\" id=\"search-box\">\n"
				+ "            <label for=\"search-box\" class=\"fas fa-search\"></label>\n"
				+ "        </form>\n"
				+ "\n"
				+ "        <div class=\"icons\">\n"
				+ "            <div id=\"search-btn\" class=\"fas fa-search\"></div>\n"
				+ "            <a href=\"#\" class=\"fas fa-heart\"></a>\n"
				+ "            <a href=\"#\" class=\"fas fa-shopping-cart\"></a>\n"
				+ "            <div class=\"dropdown\">\n"
				+ "                <div id=\"login-btn\" class=\"fas fa-user\">"+" "+user+"</div>\n"
				+ "                <div class=\"dropdown-content\">\n"
				+ "                <a href=\"index.html\">Log Out</a>\n"
				+ "                </div>\n"
				+ "            </div>\n"
				+ "        </div>\n"
				+ "\n"
				+ "    </div>\n"
				+ "\n"
				+ "    <div class=\"header-2\">\n"
				+ "        <nav class=\"navbar\">\n"
				+ "            <a href=\"#home\">home</a>\n"
				+ "            <a href=\"featured.html\">featured</a>\n"
				+ "            <a href=\"arrival.html\" target=\"blank\">arrivals</a>\n"
				+ "            <a href=\"#reviews\">reviews</a>\n"
				+ "            <a href=\"blogs.html\">blogs</a>\n"
				+ "        </nav>\n"
				+ "    </div>\n"
				+ "\n"
				+ "</header>\n"
				+ "\n"
				+ "<!-- header section ends -->\n"
				+ "\n"
				+ "<!-- bottom navbar  -->\n"
				+ "\n"
				+ "<nav class=\"bottom-navbar\">\n"
				+ "    <a href=\"#home\" class=\"fas fa-home\"></a>\n"
				+ "    <a href=\"featured.html\" class=\"fas fa-list\"></a>\n"
				+ "    <a href=\"arrival.html\" class=\"fas fa-tags\"></a>\n"
				+ "    <a href=\"#reviews\" class=\"fas fa-comments\"></a>\n"
				+ "    <a href=\"blogs.html\" class=\"fas fa-blog\"></a>\n"
				+ "</nav>\n"
				+ "\n"
				+ "<!-- login form  -->\n"
				+ "\n"
				+ "<div class=\"login-form-container\">\n"
				+ "\n"
				+ "    <div id=\"close-login-btn\" class=\"fas fa-times\"></div>\n"
				+ "\n"
				+ "    <form action=\"subscribe.html\" name=\"myform\" method=\"post\">\n"
				+ "        <h3>sign in</h3>\n"
				+ "        <span>Email Id</span>\n"
				+ "        <input type=\"email\" name=\"name\" class=\"box\" placeholder=\"enter your email\" id=\"\">\n"
				+ "        <span>password</span>\n"
				+ "        <input type=\"password\" name=\"password\" class=\"box\" placeholder=\"enter your password\" id=\"\">\n"
				+ "        <div class=\"checkbox\">\n"
				+ "            <input type=\"checkbox\" name=\"\" id=\"remember-me\">\n"
				+ "            <label for=\"remember-me\"> remember me</label>\n"
				+ "        </div>\n"
				+ "        <input type=\"submit\" value=\"sign in\" class=\"btn\">\n"
				+ "        <p>don't have an account ? <a href=\"register.html\">create one</a></p>\n"
				+ "    </form>\n"
				+ "\n"
				+ "</div>\n"
				+ "\n"
				+ "<!-- home section starts  -->\n"
				+ "\n"
				+ "<section class=\"home\" id=\"home\">\n"
				+ "\n"
				+ "    <div class=\"row\">\n"
				+ "\n"
				+ "        <div class=\"content\">\n"
				+ "            <h3>upto 75% off</h3>\n"
				+ "            <p>Get your favorite books before it is too late!!</p>\n"
				+ "            <a href=\"#\" class=\"btn\">shop now</a>\n"
				+ "        </div>\n"
				+ "\n"
				+ "        <div class=\"swiper books-slider\">\n"
				+ "            <div class=\"swiper-wrapper\">\n"
				+ "                <a href=\"#\" class=\"swiper-slide\"><img src=\"image/atomichabits.jpg\" alt=\"\"></a>\n"
				+ "                <a href=\"#\" class=\"swiper-slide\"><img src=\"image/ikigai.jpg\" alt=\"\"></a>\n"
				+ "                <a href=\"#\" class=\"swiper-slide\"><img src=\"image/hyperfocus.jpg\" alt=\"\"></a>\n"
				+ "                <a href=\"#\" class=\"swiper-slide\"><img src=\"image/12rulesfor life.jpg\" alt=\"\"></a>\n"
				+ "                <a href=\"#\" class=\"swiper-slide\"><img src=\"image/80:20principle.jpg.webp\" alt=\"\"></a>\n"
				+ "                <a href=\"#\" class=\"swiper-slide\"><img src=\"image/richdadpoordad.jpg\" alt=\"\"></a>\n"
				+ "            </div>\n"
				+ "            <img src=\"image/stand.png\" class=\"stand\" alt=\"\">\n"
				+ "        </div>\n"
				+ "\n"
				+ "    </div>\n"
				+ "\n"
				+ "</section>\n"
				+ "\n"
				+ "<!-- home section ense  -->\n"
				+ "\n"
				+ "<!-- icons section starts  -->\n"
				+ "\n"
				+ "<section class=\"icons-container\">\n"
				+ "\n"
				+ "    <div class=\"icons\">\n"
				+ "        <i class=\"fas fa-shipping-fast\"></i>\n"
				+ "        <div class=\"content\">\n"
				+ "            <h3>free shipping</h3>\n"
				+ "            <p>order over ₹999</p>\n"
				+ "        </div>\n"
				+ "    </div>\n"
				+ "\n"
				+ "    <div class=\"icons\">\n"
				+ "        <i class=\"fas fa-lock\"></i>\n"
				+ "        <div class=\"content\">\n"
				+ "            <h3>secure payment</h3>\n"
				+ "            <p>100% secure payment</p>\n"
				+ "        </div>\n"
				+ "    </div>\n"
				+ "\n"
				+ "    <div class=\"icons\">\n"
				+ "        <i class=\"fas fa-redo-alt\"></i>\n"
				+ "        <div class=\"content\">\n"
				+ "            <h3>easy returns</h3>\n"
				+ "            <p>10 days returns</p>\n"
				+ "        </div>\n"
				+ "    </div>\n"
				+ "\n"
				+ "    <div class=\"icons\">\n"
				+ "        <i class=\"fas fa-headset\"></i>\n"
				+ "        <div class=\"content\">\n"
				+ "            <h3>24/7 support</h3>\n"
				+ "            <p>call us anytime</p>\n"
				+ "        </div>\n"
				+ "    </div>\n"
				+ "\n"
				+ "</section>\n"
				+ "\n"
				+ "<!-- icons section ends -->\n"
				+ "\n"
				+ "\n"
				+ "<!-- deal section starts  -->\n"
				+ "\n"
				+ "<section class=\"deal\">\n"
				+ "\n"
				+ "    <div class=\"content\">\n"
				+ "        <h3>deal of the day</h3>\n"
				+ "        <h1>upto 50% off</h1>\n"
				+ "        <p>grab your books before the sale ends</p>\n"
				+ "        <a href=\"#\" class=\"btn\">shop now</a>\n"
				+ "    </div>\n"
				+ "\n"
				+ "    <div class=\"image\">\n"
				+ "        <img src=\"image/deal-img.jpg\" alt=\"\">\n"
				+ "    </div>\n"
				+ "\n"
				+ "</section>\n"
				+ "\n"
				+ "<!-- deal section ends -->\n"
				+ "\n"
				+ "<!-- reviews section starts  -->\n"
				+ "\n"
				+ "<section class=\"reviews\" id=\"reviews\">\n"
				+ "\n"
				+ "    <h1 class=\"heading\"> <span>client's reviews</span> </h1>\n"
				+ "\n"
				+ "    <div class=\"swiper reviews-slider\">\n"
				+ "\n"
				+ "        <div class=\"swiper-wrapper\">\n"
				+ "\n"
				+ "            <div class=\"swiper-slide box\">\n"
				+ "                <img src=\"image/Akash.jpg\" alt=\"\">\n"
				+ "                <h3>Akash M</h3>\n"
				+ "                <p>We get any type of author book student book.people should try here cheap and best cost.all type of books qvailable in this store</p>\n"
				+ "                <div class=\"stars\">\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                </div>\n"
				+ "            </div>\n"
				+ "\n"
				+ "            <div class=\"swiper-slide box\">\n"
				+ "                <img src=\"image/Aaditya.jpg\" alt=\"\">\n"
				+ "                <h3>Aaditya Maria</h3>\n"
				+ "                <p>I love to read different books , they have more beautifull , history books of wonderful aimers , really enjoyed with the books</p>\n"
				+ "                <div class=\"stars\">\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star-half-alt\"></i>\n"
				+ "                </div>\n"
				+ "            </div>\n"
				+ "\n"
				+ "            <div class=\"swiper-slide box\">\n"
				+ "                <img src=\"image/pic-3.png\" alt=\"\">\n"
				+ "                <h3>Atharva Santosh</h3>\n"
				+ "                <p>Books are very important for us. Because they teach us how to deal with different situations in our life.</p>\n"
				+ "                <div class=\"stars\">\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star-half-alt\"></i>\n"
				+ "                </div>\n"
				+ "            </div>\n"
				+ "            <div class=\"swiper-slide box\">\n"
				+ "                <img src=\"image/ronit.jpg\" alt=\"\">\n"
				+ "                <h3>Ronit Bangard</h3>\n"
				+ "                <p>This store has a big collection of lots of popular books. no doubt, we will get any book from here.</p>\n"
				+ "                <div class=\"stars\">\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                </div>\n"
				+ "            </div>\n"
				+ "\n"
				+ "            <div class=\"swiper-slide box\">\n"
				+ "                <img src=\"image/shashvat.jpg\" alt=\"\">\n"
				+ "                <h3>Shashvat Rai</h3>\n"
				+ "                <p>I have visited over there, almost all books are available. One stop shop for all books. we will get any book from here.</p>\n"
				+ "                <div class=\"stars\">\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star-half-alt\"></i>\n"
				+ "                </div>\n"
				+ "            </div>\n"
				+ "\n"
				+ "            <div class=\"swiper-slide box\">\n"
				+ "                <img src=\"image/keshav.jpg\" alt=\"\">\n"
				+ "                <h3>Keshav Somani</h3>\n"
				+ "                <p>This is the amazing book store ??. I love this is the way of treat by the customers??. All the book are awailabe in this online store.</p>\n"
				+ "                <div class=\"stars\">\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star\"></i>\n"
				+ "                    <i class=\"fas fa-star-half-alt\"></i>\n"
				+ "                </div>\n"
				+ "            </div>\n"
				+ "\n"
				+ "        </div>\n"
				+ "\n"
				+ "    </div>\n"
				+ "\n"
				+ "</section>\n"
				+ "\n"
				+ "<!-- reviews section ends -->\n"
				+ "\n"
				+ "<!-- footer section starts  -->\n"
				+ "\n"
				+ "<section class=\"footer\">\n"
				+ "\n"
				+ "    <div class=\"box-container\">\n"
				+ "\n"
				+ "        <div class=\"box\">\n"
				+ "            <h3>our locations</h3>\n"
				+ "            <a href=\"#\"> <i class=\"fas fa-map-marker-alt\"></i> india </a>\n"
				+ "        </div>\n"
				+ "\n"
				+ "        <div class=\"box\">\n"
				+ "            <h3>quick links</h3>\n"
				+ "            <a href=\"#\"> <i class=\"fas fa-arrow-right\"></i> home </a>\n"
				+ "            <a href=\"featured.html\"> <i class=\"fas fa-arrow-right\"></i> featured </a>\n"
				+ "            <a href=\"arrival.html\"> <i class=\"fas fa-arrow-right\"></i> arrivals </a>\n"
				+ "            <a href=\"#reviews\"> <i class=\"fas fa-arrow-right\"></i> reviews </a>\n"
				+ "            <a href=\"blogs.html\"> <i class=\"fas fa-arrow-right\"></i> blogs </a>\n"
				+ "        </div>\n"
				+ "\n"
				+ "        <div class=\"box\">\n"
				+ "            <h3>extra links</h3>\n"
				+ "            <a href=\"#\"> <i class=\"fas fa-arrow-right\"></i> account info </a>\n"
				+ "            <a href=\"#\"> <i class=\"fas fa-arrow-right\"></i> ordered items </a>\n"
				+ "            <a href=\"#\"> <i class=\"fas fa-arrow-right\"></i> privacy policy </a>\n"
				+ "            <a href=\"#\"> <i class=\"fas fa-arrow-right\"></i> payment method </a>\n"
				+ "            <a href=\"#\"> <i class=\"fas fa-arrow-right\"></i> our serivces </a>\n"
				+ "        </div>\n"
				+ "\n"
				+ "        <div class=\"box\">\n"
				+ "            <h3>contact info</h3>\n"
				+ "            <a href=\"#\"> <i class=\"fas fa-phone\"></i> +91 9611309909 </a>\n"
				+ "            <a href=\"#\"> <i class=\"fas fa-phone\"></i> +91 9591655777 </a>\n"
				+ "            <a href=\"#\"> <i class=\"fas fa-envelope\"></i> akashmalasetty@gmail.com </a>\n"
				+ "            <img src=\"image/worldmap.png\" class=\"map\" alt=\"\">\n"
				+ "        </div>\n"
				+ "\n"
				+ "    </div>\n"
				+ "\n"
				+ "    <div class=\"share\">\n"
				+ "        <a href=\"https://www.facebook.com/akash.malasetty.9\" class=\"fab fa-facebook-f\"></a>\n"
				+ "        <a href=\"https://twitter.com/Akash_M20\" class=\"fab fa-twitter\"></a>\n"
				+ "        <a href=\"https://www.instagram.com/akashmalasetty/\" class=\"fab fa-instagram\"></a>\n"
				+ "        <a href=\"https://www.linkedin.com/in/akash-malasetty-862588a4/\" class=\"fab fa-linkedin\"></a>\n"
				+ "        <a href=\"https://in.pinterest.com/akashmalasetty9/_saved/\" class=\"fab fa-pinterest\"></a>\n"
				+ "    </div>\n"
				+ "\n"
				+ "</section>\n"
				+ "\n"
				+ "<!-- footer section ends -->\n"
				+ "\n"
				+ "\n"
				+ "\n"
				+ "\n"
				+ "<script src=\"https://unpkg.com/swiper@7/swiper-bundle.min.js\"></script>\n"
				+ "\n"
				+ "<!-- custom js file link  -->\n"
				+ "<script src=\"script.js\"></script>\n"
				+ "\n"
				+ "</body>\n"
				+ "</html>\n"
				+ "");
				
		
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doGet(request, response);
	}

}
